version: 2
jobs:
  build:
    docker:
      - image: novemberde/dind:ubuntu-18.04
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Hello World
          command: docker run hello-world

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - test
